# Jekyll configuration for NameMyPdf website

# Site settings
# Site settings
title: NameMyPDF
description: "Stop wasting time on messy filenames. Instantly rename your academic PDFs with proper citations."
baseurl: "/name-my-pdf"
url: "https://literatecomputing.github.io"

# Theme
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Features
    url: /#features
  - title: How It Works
    url: /#how-it-works
  - title: Download
    url: /#download
  - title: Docs
    url: /docs

# Marketing content
tagline: "Your academic PDFs, perfectly named"
subtitle: "Drag. Drop. Done."
cta_primary: "Download for macOS"
cta_secondary: "View on GitHub"

# Social
github_username: literatecomputing
repository: literatecomputing/name-my-pdf

# Theme

# Color scheme (supports light, dark, or custom)

# Logo

# Navigation

# Search

# Heading anchor links

# Footer content

# Back to top link

# Footer last edited timestamp

# GitHub integration

# Aux links (top right)


# Collections

# Exclude from processing

# Plugins
