# Jekyll configuration for NameMyPdf website

# Site settings
title: NameMyPdf
description: Automatically rename academic PDFs using DOI metadata
url: "https://namemypdf.com"
baseurl: ""

# Theme
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

# Color scheme (supports light, dark, or custom)
color_scheme: light

# Logo
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
# Navigation
nav_enabled: true
nav_sort: case_insensitive

# Search
search_enabled: true
title: NameMyPDF
description: "Stop wasting time on messy filenames. Instantly rename your academic PDFs with proper citations."
url: "https://namemypdf.com"
baseurl: ""
search:
# Marketing content
tagline: "Your academic PDFs, perfectly named"
subtitle: "Drag. Drop. Done."
cta_primary: "Download for macOS"
cta_secondary: "View on GitHub"
  heading_level: 2
# Social
github_username: literatecomputing
repository: literatecomputing/name-my-pdf
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives

# Heading anchor links
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 Jay Pfaffman. Distributed under the MIT License."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# GitHub integration
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/literatecomputing/name-my-pdf"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Aux links (top right)
aux_links:
  "Download":
    - "https://github.com/literatecomputing/name-my-pdf/releases/latest"
  "GitHub":
    - "https://github.com/literatecomputing/name-my-pdf"

aux_links_new_tab: true

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
