name: Deploy Website to Bunny.net

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: docs

      - name: Build Jekyll site
        run: |
          cd docs
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Bunny.net Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: "docs/_site"
          destination: "/"
          storageZoneName: "${{ secrets.BUNNY_ZONE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_PASSWORD }}"
          accessKey: "${{ secrets.BUNNY_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_PULL_ZONE_ID }}"
          storageEndpoint: "ny.storage.bunnycdn.com" # Change to region-specific if needed (ny.storage.bunnycdn.com, etc.)
          # remove: "true"
          upload: "true"
          purgePullZone: "true"
