name: Deploy Website to Bunny.net

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: docs

      - name: Build Jekyll site
        run: |
          cd docs
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Bunny.net Storage
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: "docs/_site"
          destination: "/"
          storageZoneName: "${{ secrets.BUNNY_ZONE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_PASSWORD }}"
          accessKey: "${{ secrets.BUNNY_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.BUNNY_STORAGE_ZONE }}"
          storageEndpoint: "ny.storage.bunnycdn.com" # Change to region-specific if needed (ny.storage.bunnycdn.com, etc.)
          remove: "true"

      - name: Purge Bunny CDN Cache (optional)
        if: success()
        run: |
          # Purge the CDN cache to ensure latest content is served
          curl -X POST "https://api.bunny.net/pullzone/${{ secrets.BUNNY_PULLZONE_ID }}/purgeCache" \
            -H "AccessKey: ${{ secrets.BUNNY_ACCESS_KEY }}" \
            || echo "Cache purge failed or not configured (optional)"
