name: Test PDF Renaming

on:
  push:
    branches: [main]
    paths:
      - "normalize_filename.sh"
      - "test-pdfs/**"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [main]
    paths:
      - "normalize_filename.sh"
      - "test-pdfs/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils jq curl

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install poppler jq curl

      - name: Make test script executable
        run: chmod +x test-pdfs/test_rename.sh

      - name: Run tests
        run: ./test-pdfs/test_rename.sh

      - name: Upload test logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.os }}
          path: |
            /tmp/tmp.*/Library/Logs/NameMyPdf.log
            /tmp/tmp.*/Library/Logs/NameMyPdf-debug.log
          if-no-files-found: ignore
